price1=input("What is the price of the first item in euro's?")
price2=input("What is the price of the second item in euro's?")
price3=input("What is the price of the third item in euro's?")
price4=input("What is the price of the fourth item in euro's?")
price5=input("What is the price of the fifth item in euro's?")
subtotal=int(price1)+ int(price2)+ int(price3)+ int(price4)+ int(price5)
total=subtotal + (0.07*subtotal)
print("Subtotal: €"+str(subtotal))
print("Sales tax: €" + str(0.07*subtotal))
print("Total: €" + str(total))
